version: '3.7'

services:
  ### MySQL ###########################################
  mysql-8:
    image: becagis/mysql:${MYSQL_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME:-db}_mysql_8
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
      - MYSQL_USER=${MYSQL_USER:-mysql}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-mysql@123}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-mysql@123}
    volumes:
      - ${MYSQL_VOL:-/data/becavol/mysql-8}:/var/lib/mysql
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    restart: on-failure
    networks:
      - dbadmin_default

  ### PostgreSQL ##############################################
  postgis-13-3.1:
    image: kartoza/postgis:13-3.1
    container_name: ${COMPOSE_PROJECT_NAME:-db}_postgis_1331
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASS=${POSTGRES_PASSWORD:-postgres@123}
      - TIMEZONE=${TIMEZONE:-Asia/Ho_Chi_Minh}
      - POSTGRES_MULTIPLE_EXTENSIONS=${POSTGRES_MULTIPLE_EXTENSIONS:-postgis,hstore,postgis_topology,postgis_raster,pgrouting,unaccent}
    volumes:
      - ${POSTGRES_VOL:-/data/becavol/postgis-13-3.1}:/var/lib/postgresql
    ports:
      - '5331:5432'
    restart: on-failure
    networks:
      - dbadmin_default

networks:
  dbadmin_default:
    external: true
