version: '3.7'

services:
  ### phpMyAdmin ###########################################
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME:-600}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT:-500M}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT:-2G}