version: '3.7'

services:
  ### phpMyAdmin ###########################################
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME:-600}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT:-500M}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT:-2G}

  ### pgAdmin ##############################################
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.com}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-pgadmin@123}'
    volumes:
      - ${DATA_PATH_HOST:-/data/becadock/pgadmin}:/var/lib/pgadmin