version: "3.7"

services:
  phpmyadmin:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
#    ports:
#      - "${PGADMIN_PORT:-80}:80"
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER:-pma}
      - MYSQL_PASSWORD=${PMA_PASSWORD:-pma@123}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD:-pma@123}
      - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME:-600}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT:-500M}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT:-2G}